env:
  browser: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
extends: kraftwerk28
rules:
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/react-in-jsx-scope: error
  react/void-dom-elements-no-children: error
  react/no-children-prop: error
  react/no-this-in-sfc: error
  react/no-deprecated: error
  react/no-unknown-property: error
  react/style-prop-object: error
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/prop-types:
    - error
    - skipUndeclared: true
  react/jsx-closing-bracket-location: error
  react/jsx-closing-tag-location: error
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-filename-extension: error
  react/jsx-first-prop-new-line: error
  react/jsx-indent:
    - error
    - 2
    - checkAttributes: true
      indentLogicalExpressions: true
  react/jsx-key: error
  react/jsx-max-props-per-line: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-undef: error
  react/jsx-one-expression-per-line:
    - error
    - allow: single-child
  react-hooks/rules-of-hooks: error
plugins:
  - react
  - react-hooks
